// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import "dotenv/config";  

// I did this thing to remove annoying typescript error 
const dbUrl = process.env.DATABASE_URL;
if(!dbUrl){
  throw new Error(
    "Missing required environment variables DATABASE_URL"
  )
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
